---
- name: "Get Data From IOS Device"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Get device config"
      ios_command:
        commands: "show running-config"
      register: cli_result_config
    
    - name: "Create outputs folder"
      file:
        path: "/tmp/outputs/IOS"  # Use /tmp in AWX
        state: directory
      run_once: true
      delegate_to: localhost
    
    - name: "Write config to file"
      copy:
        content: "{{ cli_result_config.stdout[0] }}\n"
        dest: "/tmp/outputs/IOS/{{inventory_hostname}}.cfg"
      delegate_to: localhost
    
    - name: "Display backup location"
      debug:
        msg: "Config backed up to /tmp/outputs/IOS/{{inventory_hostname}}.cfg"
