---
- name: Configure domain name (Fallback - No Collections Required)
  hosts: all
  gather_facts: true
  vars:
    domain_name: "testdomain.com"
    backup_dir: "/tmp/router_backups"
    
  tasks:
    - name: Create backup directory
      ansible.builtin.file:
        path: "{{ backup_dir }}/{{ inventory_hostname }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      
