---
- name: Backup Cisco IOS running configuration
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    cnos_backup:
      configType: running-config
      protocol: "ftp"
      serverip: "192.168.201.131"
