---
- name: Configure domain name
  hosts: all
  gather_facts: false
  tasks:
    - name: Print date and time
      ansible.builtin.debug:
        msg: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S')}}"
    
    - name: Configure domain
      ios_config:
        lines: ip domain name testdomain.com
        backup: yes
      register: domain_config
    
    - name: Print Command Output
      ansible.builtin.debug:
        msg: "{{ domain_config }}"
