---
- name: Backup Cisco IOS running configuration
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
  - name: run show version on remote devices
    cisco.ios.ios_command:
     commands:
     - show version 
